[status]
disabled = false

[character]
format = "ğŸ¦€ $symbol"

[git_branch]
always_show_remote=true
style='bold blue'

[git_commit]
only_detached = false

[python]
symbol = 'ğŸ '
# pyenv_version_name = true
python_binary = ['./venv/bin/python', 'python', 'python3', 'python2']

[aws]
disabled=true

[gcloud]
disabled=true
