add_newline = false
command_timeout = 1000
scan_timeout = 1000

[aws]
disabled = true

[battery]
format = "[$symbol $percentage]($style) "
empty_symbol = "ğŸª«"
charging_symbol = "ğŸ”‹"
full_symbol = 'ğŸ”‹'

[[battery.display]]
threshold = 10
style = 'red'

[bun]
disabled = true

[character]
error_symbol = "[âœ—](bold #ff5555)"
success_symbol = "[âœ](bold #50fa7b)"

[cmd_duration]
style = "bold #f1fa8c"

[directory]
style = "bold #50fa7b"

[direnv]
disabled = true

[git_branch]
always_show_remote=true
style = "bold #ff79c6"
symbol = "î‚  "

[git_commit]
only_detached = false

[git_metrics]
disabled = false

[git_status]
style = "bold #ff5555"

[python]
symbol = 'ğŸ '
# pyenv_version_name = true
python_binary = ['./.venv/bin/activate', './venv/bin/python', 'python', 'python3', 'python2']
format = '| [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[hostname]
style = "bold #bd93f9"

[kubernetes]
disabled = true

[nodejs]
format = 'via [ğŸ¤– $version](bold green) '

[package]
disabled = true

[username]
format = "[$user]($style) on "
style_user = "bold #8be9fd"
disabled = false
show_always = true

[docker_context]
format = '| [$symbol$context]($style) '

[terraform]
format = '| [$symbol$workspace]($style) '
